version: '3.4'

services:

  mongo:
    restart: always
    volumes:
      - /netrunner/mongodb_data:/data/db
    networks:
      - traefik

  netrunner.server:
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netrunner_server.rule=Host(`${NETRUNNER_BASE_URL}`)"
      - "traefik.http.services.netrunner_server.loadbalancer.server.port=80"
      - "traefik.http.routers.netrunner_server.tls.certresolver=letsencrypt"
      - "traefik.http.routers.netrunner_server.middlewares=netrunner_server"
      - "traefik.http.middlewares.netrunner_server.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.netrunner_server.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.netrunner_server.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.netrunner_server.headers.accessControlAllowMethods=*"
    networks:
      - traefik
      
networks:
  traefik:
    external:
      name: traefik_webgateway
