version: '3.4'

services:
  netrunner.server:
    image: ${DOCKER_REGISTRY-}netrunnerserver
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on: 
      - mongo
  mongo:
    image: mongo