version: '3.4'

services:

  netrunner.server_legacy:
    image: netrunnerserver
    build:
      context: .
      dockerfile: ServerLegacy/Dockerfile
    depends_on: 
      - mongo
      - crossbar
    environment: 
      - WAMP_INTERNAL_TICKET

  netrunner.auth:
    image: netrunnerauth
    build:
      context: .
      dockerfile: Auth/Dockerfile
    environment: 
      - WAMP_INTERNAL_TICKET
    depends_on:
      - mongo
      - crossbar

  #netrunner.client:
  #  image: netrunnerclient
  #  build:
  #    context: .
  #    dockerfile: Client.dockerfile
  #  depends_on: 
  #    - netrunner.server
  #  environment:
  #    - NETRUNNER_BASE_URL

  #netrunner.challenges:
  #  image: netrunnerchallenges
  #  build:
  #    context: .
  #    dockerfile: Challenges.dockerfile
  #  depends_on: 
  #    - netrunner.server
  #  environment:
  #    - NETRUNNER_BASE_URL

  crossbar:
    build:
      context: ./crossbar
    environment: 
      - WAMP_INTERNAL_TICKET

  mongo:
    image: mongo

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    environment: 
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      "start-dev"

  openldap:
    image: bitnami/openldap:2
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ROOT=dc=netrunner,dc=local
      - LDAP_ALLOW_ANON_BINDING=false
      - LDAP_GROUP=