version: '3.4'

services:

  mongo:
    image: mongo:4.4.17

  netrunner.server:
    image: ${DOCKER_REGISTRY-}netrunnerserver
    build:
      context: .
      dockerfile: Netrunner.Server/Dockerfile

