version: '3.4'

services:
  netrunner.server:
    image: ${DOCKER_REGISTRY-}netrunnerserver
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - mongo
    restart: always
  mongo:
    image: mongo
    volumes:
      - ./mongodb_data:/data/db
    restart: always