version: '3.4'

services:

  mongo:
    volumes:
      - /netrunner/mongodb_data:/data/db
    networks:
      - traefik

  netrunner.server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netrunner_server.rule=Host(`${NETRUNNER_BASE_URL}`)"
      - "traefik.http.services.netrunner_server.loadbalancer.server.port=80"
      - "traefik.http.routers.dedros.tls.certresolver=letsencrypt"
    networks:
      - traefik
      
networks:
  traefik:
    external:
      name: traefik_webgateway