version: '3.4'

services:

  traefik:
    image: traefik:v2.4
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"
    command: --api.insecure=true --providers.docker

  mongo:
    volumes:
      - ./mongodb_data_dev:/data/db
    ports:
      - "27017:27017"

  netrunner.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    labels:
      - "traefik.http.routers.netrunner_server.rule=Host(`${NETRUNNER_BASE_URL}`)"
      - "traefik.http.services.netrunner_server.loadbalancer.server.port=80"
