version: '3.4'

services:
  traefik:
    ports:
      - "80:80"
      - "8080:8080"
    command: --api.insecure=true --providers.docker
  netrunner.server:
    environment:
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    labels:
      - "traefik.http.routers.server.rule=Host(`api.netrunner.localhost`)"
      - "traefik.http.services.server.loadbalancer.server.port=80"
  netrunner.client:
    labels:
      - "traefik.http.routers.client.rule=Host(`app.netrunner.localhost`)"
      - "traefik.http.services.client.loadbalancer.server.port=80"
    #ports: 
    #  - "8081:80"
  netrunner.challenges:
    labels:
      - "traefik.http.routers.challenges.rule=Host(`challenges.netrunner.localhost`)"
      - "traefik.http.services.challenges.loadbalancer.server.port=80"
    #ports: 
    #  - "8082:80"
  crossbar:
    labels:
      - "traefik.http.routers.crossbar.rule=Host(`wamp.netrunner.localhost`)"
      - "traefik.http.services.crossbar.loadbalancer.server.port=8080"
    volumes:
      - ./crossbar:/node/.crossbar
  mongo:
    volumes:
      - ./mongodb_data:/data/db