version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=netrunner
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=OdyiSTATeRYe
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - '27017-27019:27017-27019'
    restart: always