version: '3.4'

services:
  netrunner.server:
    environment:
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80:80"
      #- "443:443"
    #volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: always
  mongo:
    volumes:
      - ./mongodb_data:/data/db
    restart: always
