version: '3.4'

services:
  traefik:
    profiles:
      - donotstart
  netrunner.server:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - NETRUNNER_BASE_URL
      - WAMP_INTERNAL_TICKET
    labels:
      - "traefik.http.routers.server.rule=Host(`api.${NETRUNNER_BASE_URL}`)"
      - "traefik.http.services.server.loadbalancer.server.port=80"
  netrunner.client:
    labels:
      - "traefik.http.routers.client.rule=Host(`app.${NETRUNNER_BASE_URL}`)"
      - "traefik.http.services.client.loadbalancer.server.port=80"
    #ports: 
    #  - "8081:80"
  netrunner.challenges:
    labels:
      - "traefik.http.routers.challenges.rule=Host(`challenges.${NETRUNNER_BASE_URL}`)"
      - "traefik.http.services.challenges.loadbalancer.server.port=80"
    #ports: 
    #  - "8082:80"
  crossbar:
    labels:
      - "traefik.http.routers.crossbar.rule=Host(`wamp.${NETRUNNER_BASE_URL}`)"
      - "traefik.http.services.crossbar.loadbalancer.server.port=8080"
    volumes:
      - ${PWD}/crossbar/config.json:/node/.crossbar/config.json
  mongo:
    volumes:
      - /netrunner/mongodb_data:/data/db