version: '3.4'

services:

  mongo:
    volumes:
      - /netrunner/mongodb_data:/data/db
    networks:
      - traefik

  netrunner.server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netrunner_server.rule=Host(`${NETRUNNER_BASE_URL}`)"
      - "traefik.http.services.netrunner_server.loadbalancer.server.port=80"
      - "traefik.http.routers.netrunner_server.tls.certresolver=letsencrypt"
      - "traefik.http.routers.netrunner_server.middlewares=netrunner_server"
      - "traefik.http.middlewares.netrunner_server.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST"
      - "traefik.http.middlewares.netrunner_server.headers.accesscontrolalloworigin=`*`"
      - "traefik.http.middlewares.netrunner_server.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.netrunner_server.headers.addvaryheader=true"
    networks:
      - traefik
      
networks:
  traefik:
    external:
      name: traefik_webgateway